language: python
python:
  - "3.5"
sudo: required
services:
  - docker
before_install:
  - docker build -t  nkirui2030/softdjangoweb .
script: skip

after_success:
# am using a single image
# login to docker cli
  - echo "&DOCKER_PASSWORD" | docker login  -u "$DOCKER_ID" --password -stdin
  - docker push nkirui2030/softdjangoweb 

deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "softsearchdjango"
  env: "Softsearchdjango-env"
  bucket_name: "elasticbeanstalk-us-west-1-736702276294"
  bucket_path: "softsearchdjango"
  skip_cleanup: true

  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
  

